name: Build and deploy JAR app to Azure Web App - AMBank
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven (skip tests)
        run: mvn -f AnhembiMorumBank/pom.xml -B -DskipTests=true clean package

      - name: Show target folder (debug)
        run: |
          echo "== present working dir =="
          pwd
          echo "== list root =="
          ls -la
          echo "== list AnhembiMorumBank =="
          ls -la AnhembiMorumBank || true
          echo "== list AnhembiMorumBank/target =="
          ls -la AnhembiMorumBank/target || true
          echo "== find any jars under workspace =="
          find . -type f -name "*.jar" -maxdepth 6 -print || true

      - name: Upload artifact for deployment job (all jars)
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '**/target/*.jar'   # pega qualquer JAR dentro de qualquer target/

  deploy:
    need
